### ISSUE TITLE
Evitar erro de ausência de histórico do periódico

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac_5#188]
### Descrição da tarefa
Evitar erro de ausência de histórico do periódico

```
ERROR:root:list index out of range
Traceback (most recent call last):
  File "/app/opac/webapp/main/views.py", line 2141, in journal
    journal = controllers.add_journal(payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opac/webapp/controllers.py", line 1937, in add_journal
    journal = JournalFactory(data)
              ^^^^^^^^^^^^^^^^^^^^
  File "/app/opac/webapp/factory.py", line 87, in JournalFactory
    journal.current_status = metadata.get("status_history", [{}])[-1].get("status")
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
```

**Comment by robertatakenaka** [comment]
já foi resolvido
